services:
  - type: web
    name: ms-teams-meeting-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MS_APP_ID
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: PORT
        value: https://team-meetings.onrender.com
    healthCheckPath: /health
